---
- name: "breaking-change"
  color: ee0701
  description: "A breaking change for existing users."
- name: "hotfix"
  color: ee0701
  description: "A critical issue that needs to be deployed immediately."
- name: "bugfix"
  color: ee0701
  description: "Inconsistencies or issues which will cause a problem for users or implementors."
- name: "documentation"
  color: 0052cc
  description: "Solely about the documentation of the project."
- name: "enhancement"
  color: 1d76db
  description: "Enhancement of the code, not introducing new features."
- name: "refactor"
  color: 1d76db
  description: "Improvement of existing code, not introducing new features."
- name: "performance"
  color: 1d76db
  description: "Improving performance, not introducing new features."
- name: "new-feature"
  color: 0e8a16
  description: "New features or options."
- name: "maintenance"
  color: 2af79e
  description: "Generic maintenance tasks."
- name: "ci"
  color: 1d76db
  description: "Work that improves the continue integration."
- name: "dependencies"
  color: 1d76db
  description: "Upgrade or downgrade of project dependencies."
- name: "security"
  color: ee0701
  description: "Marks a security issue that needs to be resolved asap."

- name: "skip-changelog"
  color: fef2c0
  description: "This issue or PR is exempted from the release notes."
- name: "skip-deployment"
  color: fef2c0
  description: "This prevents the merge from executing deploy hooks on the webhooks server."
- name: "development"
  color: 5319e7
  description: "This PR is deployed to the development environment."

- name: "major"
  color: b60205
  description: "This PR causes a major version bump in the version number."
- name: "minor"
  color: 0e8a16
  description: "This PR causes a minor version bump in the version number."
